### ISSUE TITLE
CIR task

### ISSUE THREAD

**Issue by likeucode** [owj0421/OutfitTransformer#1]
Hi,bro, when CIR task is Available?

**Comment by bigohofone** [comment]
I can't train the model because I have nowhere else to get the resources. 
Also, since I'm refactoring the code as a whole, I'm going to create a code that you can train cir by your own soon. Thank you for your interest.

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-01-24 (수) 11:48:15 (GMT+09:00)
Subject: [owj0421/outfit-transformer] CIR task (Issue #1)

Hi,bro, when CIR task is Available?

**Comment by likeucode** [comment]
> I can't train the model because I have nowhere else to get the resources. Also, since I'm refactoring the code as a whole, I'm going to create a code that you can train cir by your own soon. Thank you for your interest.
> […](#)
> -----Original Message----- From: ***@***.***> To: ***@***.***>; Cc: ***@***.***>; Sent: 2024-01-24 (수) 11:48:15 (GMT+09:00) Subject: [owj0421/outfit-transformer] CIR task (Issue #1) Hi,bro, when CIR task is Available? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Alright, looking forward to your new version

**Comment by bigohofone** [comment]
Sorry for the late answer. First of all, I uploaded a training code for CIR task. If you are on enough GPU to train for CP, try fine-tuning with that code for CIR task. Note that the code has not been trained substantially yet, so learning may experience errors. If you let me know the error that occurs, I will correct it right away.

Oh! Also, I haven't written the evaluation code for CIR yet. I'm confused about how to make it, so it'll take some time. Please let me know if there's a good way.

**Comment by bigohofone** [comment]
Hello, thank you for your interest in my repository.

Sorry for the late reply.

I corrected all errors and uploaded them into code.

Please refer to the various methods of learning and evaluation along with the demo file on the readme.

In the case of CIR
Using the description of the Target Item is called Data leakage, and we learned that it is not used,

Although we are looking for suitable items that are currently an alternative, we are planning to add a function to filter the items to be searched through "category".

Thank you.

Please let me know if there is anything strange.
