### ISSUE TITLE
Checkpoints!!

### ISSUE THREAD

**Issue by Inam-tech** [owj0421/OutfitTransformer#11]
I faced problem when u made run , i could not download checkpoints page it is not available 
plz help me (inam.alsanawi@gmail.com)

**Comment by Chippa-Rohith** [comment]
did you had any luck with the checkpoints

**Comment by bigohofone** [comment]
Sorry for late.

plz download from the link below.

https://drive.google.com/drive/folders/1cMTvmC6vWV9F9j08GX1MppNm6DDnSiZl?usp=drive_link
