### ISSUE TITLE
Git lfs exceeded quota

### ISSUE THREAD

**Issue by Wayfarer123** [owj0421/OutfitTransformer#2]
When trying to download weights for the model, I got the following error: 
'''
Error downloading object: checkpoints/cp/2023-12-27/1_0.923.pth (f1c8681): Smudge error: Error downloading checkpoints/cp/2023-12-27/1_0.923.pth (f1c8681f63b4b5875febcf7a3c8bd06716e06c5d8b288ac85bdbb76445e3c4ef): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access
''' 
I'm not very familiar with git, but as I understand, issue is on your side. If you cannot solve it or it requires payment you do not wish to do, please share weights somewhere else, for instance on GoogleDrive. I would really want to use this model for my BS Thesis, but do not have enough resourses to train it from scratch.

**Comment by bigohofone** [comment]
Give me email plz. I'll send it to you!

**Comment by Wayfarer123** [comment]
nikitaokhotnikov@mail.ru
or Telegram: https://t.me/Nikita_Okhotnikov

**Comment by bigohofone** [comment]
sent it to you. Thx for interest

**Comment by Mayor2305** [comment]
I am also facing the same issue, can I get the checkpoint weights as well? also where are the weights, I couldn't find them in the repo

**Comment by bigohofone** [comment]
Um... Cuz I refactored all code, I have to re-train all the stuffs... It'll takes some time... Do you need it urgently now? I think CP checkpoint will take about 1 week and CIR will take about 2 weeks.

**Comment by bigohofone** [comment]
After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest!
