### ISSUE TITLE
implementing using colab

### ISSUE THREAD

**Issue by FerasTB** [owj0421/OutfitTransformer#5]
hi , i wanna implement this paper for my graduation uni and my country has a pad internet so is their any instructions about how to load the dataset into colab and use this implementation ?
the problem i faced in colab that i cant install python 3.9.14 and when i skip this the error relased No module named 'torch._custom_ops'
thank

**Comment by bigohofone** [comment]
Here's my Tips!
Actually, I trained the model on the colab environment also! So, It's not that complicated to run code on colab.

1. Downgrade python -> Look https://stackoverflow.com/questions/76837647/how-to-downgrade-python-version-to-3-9-in-colab-without-creating-virtual-environ
2. In the case of the dataset, use Google drive. but, Just importing the whole dataset folder will take a lot of time. if you zip it and upload it as zip(or other form like .tar), will save you a lot of time! and run Python code to unzip on Google Drive.

**Comment by FerasTB** [comment]
I appreciate your Tips it was helpful for python version but can you explain what the data file should contain?
I retrieve the structure from Google Drive https://drive.google.com/drive/folders/0B4Eo9mft9jwoVDNEWlhEbUNUSE0?resourcekey=0-vQg9TMSLKnmPCuuWwl5Ebw
and the images from Kaggel https://www.kaggle.com/datasets/dnepozitek/maryland-polyvore-images/data
What should I do next?

**Comment by bigohofone** [comment]
one with Google drive is what i used. Just unzip in your drive and, sent that path to train.py! that's all.

**Comment by FerasTB** [comment]
it is work with this data https://www.kaggle.com/datasets/dnepozitek/polyvore-outfits
thank you so much :)

**Comment by Inam-tech** [comment]
> hi , i wanna implement this paper for my graduation uni and my country has a pad internet so is their any instructions about how to load the dataset into colab and use this implementation ? the problem i faced in colab that i cant install python 3.9.14 and when i skip this the error relased No module named 'torch._custom_ops' thank

are you implemented this code, is it work successfuly ? you can help me plz
