### ISSUE TITLE
CP task 

### ISSUE THREAD

**Issue by FerasTB** [owj0421/OutfitTransformer#6]
Please i really need a solution, i tried a lot to make predictions using the model i trained for cp task and it always come with tensor dim error 
I have university project and i should do this step so please can anyone provides a code for how the right way is ?
For example if i have a top and bottom image with text for each image how i can make predictions ?

**Comment by bigohofone** [comment]
Hi, Did you use src/datasets/processor DeepFashionInputProcessor ?

**Comment by FerasTB** [comment]
Hi 
Yse i use it and use the image processor in the same file too 
Can you provide a code snipe for example of the model take 3 image from user and return cp score ?
Thanks 🙏🏻

**Comment by bigohofone** [comment]
sry for late. I'm trying to make some examples to run in your custom datasets. but, may be it i'll takes some time...

**Comment by bigohofone** [comment]
After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest!

**Comment by FerasTB** [comment]
That's awesome 🙏🏻
I really appreciate your work , thanks 🔥

**Comment by zztMermory** [comment]
> After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest!

 Hi~is CIR checkpoint named fitb_acc0.64.pth ?

**Comment by bigohofone** [comment]
you're right. However, the part using the target description was omitted, and only fitb was evaluated. Unlike the original paper, since it was learned with information in a large batch size, the performance will probably be good. Please let me know if you evaluate it.

-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2024. 6. 12 오후 3:56:00
제목: Re: [owj0421/OutfitTransformer] CP task (Issue #6)


After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest!

Hi~is CIR checkpoint named fitb_acc0.64.pth ?

**Comment by zztMermory** [comment]
> you're right. However, the part using the target description was omitted, and only fitb was evaluated. Unlike the original paper, since it was learned with information in a large batch size, the performance will probably be good. Please let me know if you evaluate it.
> […](#)
> -----Original Message----- 보낸사람: ***@***.***> 받는사람: ***@***.***> 참조: ***@***.***>, ***@***.***> 날짜: 2024. 6. 12 오후 3:56:00 제목: Re: [owj0421/OutfitTransformer] CP task (Issue #6) After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest! Hi~is CIR checkpoint named fitb_acc0.64.pth ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

OK.I am evaluating and reply.
I find that you change Resnet-18 to Fashion-clip when backbone. I wonder the preformance when using Fashion-clip.

Thank you~

**Comment by zztMermory** [comment]
> you're right. However, the part using the target description was omitted, and only fitb was evaluated. Unlike the original paper, since it was learned with information in a large batch size, the performance will probably be good. Please let me know if you evaluate it.
> […](#)
> -----Original Message----- 보낸사람: ***@***.***> 받는사람: ***@***.***> 참조: ***@***.***>, ***@***.***> 날짜: 2024. 6. 12 오후 3:56:00 제목: Re: [owj0421/OutfitTransformer] CP task (Issue #6) After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest! Hi~is CIR checkpoint named fitb_acc0.64.pth ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

OK.I am evaluating and reply.
I find that you change Resnet-18 to Fashion-clip when backbone. I wonder the performance when using Fashion-clip.

Thank you~

**Comment by zztMermory** [comment]
> > you're right. However, the part using the target description was omitted, and only fitb was evaluated. Unlike the original paper, since it was learned with information in a large batch size, the performance will probably be good. Please let me know if you evaluate it.
> > […](#)
> > -----Original Message----- 보낸사람: _**@**_._**> 받는사람: _**@**_.**_> 참조: _**@**_._**>, _**@**_.**_> 날짜: 2024. 6. 12 오후 3:56:00 제목: Re: [owj0421/OutfitTransformer] CP task (Issue #6) After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest! Hi~is CIR checkpoint named fitb_acc0.64.pth ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> OK.I am evaluating and reply. I find that you change Resnet-18 to Fashion-clip when backbone. I wonder the performance when using Fashion-clip.
> 
> Thank you~
Hi! I evaluated on CIR task. But it doesn't work even though using the target description.
I suspect there are two potential reasons: 1) negative samples, 2) image-text fusion.
Looking forward to your response！

**Comment by zztMermory** [comment]
> > you're right. However, the part using the target description was omitted, and only fitb was evaluated. Unlike the original paper, since it was learned with information in a large batch size, the performance will probably be good. Please let me know if you evaluate it.
> > […](#)
> > -----Original Message----- 보낸사람: _**@**_._**> 받는사람: _**@**_.**_> 참조: _**@**_._**>, _**@**_.**_> 날짜: 2024. 6. 12 오후 3:56:00 제목: Re: [owj0421/OutfitTransformer] CP task (Issue #6) After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest! Hi~is CIR checkpoint named fitb_acc0.64.pth ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> OK.I am evaluating and reply. I find that you change Resnet-18 to Fashion-clip when backbone. I wonder the performance when using Fashion-clip.
> 
> Thank you~

Hi! 
I examed no CIR task. But it doesn't work even though using target discription.
I suspect there are two potential reasons: 1) negative samples, 2) image-text fusion
Looking forward to your response!
