### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by miniwa00** [owj0421/OutfitTransformer#8]
안녕하세요!
Thanks for your great work!
I think your Readme is deprecated :( There is no train.py and args are not available anymore. 
+) I've downloaded dataset from polyvore but it doesn't match with your script. Can you let me know the exact dataset tree & configuration?

**Comment by bigohofone** [comment]
Hello, thank you for your interest in my repository.

Sorry for the late reply.

I corrected all errors and uploaded them into code.

Please refer to the various methods of learning and evaluation along with the demo file on the readme.

In the case of CIR
Using the description of the Target Item is called Data leakage, and we learned that it is not used,

Although we are looking for suitable items that are currently an alternative, we are planning to add a function to filter the items to be searched through "category".

Thank you.

Please let me know if there is anything strange.
