### ISSUE TITLE
CIR TASK doesn't work

### ISSUE THREAD

**Issue by zztMermory** [owj0421/OutfitTransformer#9]
> > you're right. However, the part using the target description was omitted, and only fitb was evaluated. Unlike the original paper, since it was learned with information in a large batch size, the performance will probably be good. Please let me know if you evaluate it.
> > […](#)
> > -----Original Message----- 보낸사람: _**@**_._**> 받는사람: _**@**_.**_> 참조: _**@**_._**>, _**@**_.**_> 날짜: 2024. 6. 12 오후 3:56:00 제목: Re: [owj0421/OutfitTransformer] CP task (Issue #6) After modifying the code, I updated the required checkpoints for CP and CIR. We ask for your interest! Hi~is CIR checkpoint named fitb_acc0.64.pth ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> OK.I am evaluating and reply. I find that you change Resnet-18 to Fashion-clip when backbone. I wonder the performance when using Fashion-clip.
> 
> Thank you~

Hi! 
I examed no CIR task. But it doesn't work even though using target discription.
I suspect there are two potential reasons: 1) negative samples, 2) image-text fusion
Looking forward to your response!

_Originally posted by @zztMermory in https://github.com/owj0421/OutfitTransformer/issues/6#issuecomment-2258452173_

**Comment by bigohofone** [comment]
Hello, thank you for your interest in my repository.

Sorry for the late reply.

I corrected all errors and uploaded them into code.

Please refer to the various methods of learning and evaluation along with the demo file on the readme.

In the case of CIR
Using the description of the Target Item is called Data leakage, and we learned that it is not used,

Although we are looking for suitable items that are currently an alternative, we are planning to add a function to filter the items to be searched through "category".

Thank you.

Please let me know if there is anything strange.
